# Generated by Django 4.1.2 on 2022-11-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0002_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbolista',
            name='nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
